### ISSUE TITLE
Question: How to create fat jar for this project using liberty-maven-plugin?

### ISSUE THREAD

**Issue by rohanKanojia** [OpenLiberty/sample-getting-started#45]
Hi, I'm from [Eclipse JKube](https://github.com/eclipse/jkube) team. We help Java developers deploy their applications onto Kubernetes/OpenShift. We already have support for OpenLiberty in Eclipse JKube. Here is our OpenLiberty quickstart: https://github.com/eclipse/jkube/tree/master/quickstarts/maven/openliberty

I was trying to deploy this application to Kubernetes using Eclipse JKube but somehow I'm stuck at configuring liberty maven plugin to create correct fat jar. Here is my plugin configuration:
```
            <!-- Enable liberty-maven plugin -->
            <plugin>
                <groupId>io.openliberty.tools</groupId>
                <artifactId>liberty-maven-plugin</artifactId>
                <version>3.0.1</version>

                <configuration>
                    <configFile>src/main/liberty/config/server.xml</configFile>
                    <assemblyArtifact>
                        <groupId>io.openliberty</groupId>
                        <artifactId>openliberty-runtime</artifactId>
                        <version>[18.0.0.1,)</version>
                        <type>zip</type>
                    </assemblyArtifact>
                    <bootstrapProperties>
                        <default.http.port>${http.port}</default.http.port>
                        <default.https.port>${https.port}</default.https.port>
                        <app.context.root>/</app.context.root>
                    </bootstrapProperties>
                </configuration>
                <executions>
                    <execution>
                        <id>create</id>
                        <phase>package</phase>
                        <goals>
                            <goal>create</goal>
                            <goal>deploy</goal>
                            <goal>package</goal>
                        </goals>
                        <configuration>
                            <looseApplication>true</looseApplication>
                            <stripVersion>true</stripVersion>
                            <installAppPackages>project</installAppPackages>
                            <packageName>io-openliberty-sample-getting-started</packageName>
                            <packageType>jar</packageType>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

```

This create a fat jar but when I run it, I get this error:
```
work/repos/sample-getting-started : $ java -jar target/io-openliberty-sample-getting-started.ja 
Extracting files to /home/rohaan/wlpExtract/io-openliberty-sample-getting-started_5177235419688/wlp
Successfully extracted all product files.
Launching defaultServer (Open Liberty 20.0.0.8/wlp-1.0.43.cl200820200721-1900) on Java HotSpot(TM) 64-Bit Server VM, version 14.0.1+7 (en_US)
[AUDIT   ] CWWKE0001I: The server defaultServer has been launched.
[AUDIT   ] CWWKG0093A: Processing configuration drop-ins resource: /home/rohaan/wlpExtract/io-openliberty-sample-getting-started_5177235419688/wlp/usr/servers/defaultServer/configDropins/defaults/install_apps_configuration_1491924271.xml
[ERROR   ] CWWKG0075E: The value  is not valid for attribute httpPort of configuration element httpEndpoint. The validation message was: Value "" is not a number..
[AUDIT   ] CWWKZ0058I: Monitoring dropins for applications.
Java HotSpot(TM) 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
[WARNING ] CWWKZ0014W: The application io.openliberty.sample.getting.started could not be started as it could not be found at location io.openliberty.sample.getting.started.war.
[AUDIT   ] CWWKS4104A: LTPA keys created in 2.430 seconds. LTPA key file: /home/rohaan/wlpExtract/io-openliberty-sample-getting-started_5177235419688/wlp/usr/servers/defaultServer/resources/security/ltpa.keys
[AUDIT   ] CWPKI0803A: SSL certificate created in 3.564 seconds. SSL key file: /home/rohaan/wlpExtract/io-openliberty-sample-getting-started_5177235419688/wlp/usr/servers/defaultServer/resources/security/key.p12
[err] java.io.FileNotFoundException: /home/rohaan/wlpExtract/io-openliberty-sample-getting-started_5177235419688/wlp/usr/servers/defaultServerresources/CustomConfigSource.json (No such file or directory)
[err] 	at java.base/java.io.FileInputStream.open0(Native Method)
[err] 	at java.base/java.io.FileInputStream.open(FileInputStream.java:212)
[err] 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:154)
[err] 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:109)
[err] 	at java.base/java.io.FileReader.<init>(FileReader.java:60)
[err] 	at io.openliberty.sample.config.CustomConfigSource.readFile(CustomConfigSource.java:86)
[err] 	at io.openliberty.sample.config.CustomConfigSource.getProperties(CustomConfigSource.java:52)
[err] 	at io.openliberty.sample.config.CustomConfigSource.getOrdinal(CustomConfigSource.java:32)
[err] 	at com.ibm.ws.microprofile.config.impl.ConfigSourceComparator.compare(ConfigSourceComparator.java:38)
[err] 	at [internal classes]
[err] 	at java.base/java.util.TreeMap.put(TreeMap.java:550)
[err] 	at java.base/java.util.TreeSet.add(TreeSet.java:255)
[err] 	at com.ibm.ws.microprofile.config.impl.SortedSourcesImpl.add(SortedSourcesImpl.java:77)
[err] 	at [internal classes]
[err] 	at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:336)
[err] 	at com.ibm.ws.microprofile.config14.impl.Config14BuilderImpl.getSources(Config14BuilderImpl.java:52)
[err] 	at [internal classes]
[err] 	at org.eclipse.microprofile.config.ConfigProvider.getConfig(ConfigProvider.java:105)
[err] 	at com.ibm.ws.microprofile.config.cdi.ConfigCDIExtension.processConversionType(ConfigCDIExtension.java:153)
[err] 	at [internal classes]
[err] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[err] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[err] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[err] 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[err] 	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
[err] 	at [internal classes]
[err] 	at javax.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:124)
[err] 	at org.jboss.weld.util.Observers.notify(Observers.java:166)
[err] 	at [internal classes]
[err] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[err] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[err] 	at java.base/java.lang.Thread.run(Thread.java:832)
[ERROR   ] CWMCG5003E: The [BackedAnnotatedField] @Inject @ConfigProperty io.openliberty.sample.system.SystemConfig.inMaintenance InjectionPoint dependency was not resolved. Error: java.lang.NumberFormatException: null
	at java.base/java.lang.Integer.parseInt(Integer.java:614)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at io.openliberty.sample.config.CustomConfigSource.getOrdinal(CustomConfigSource.java:32)
	at com.ibm.ws.microprofile.config.impl.ConfigSourceComparator.compare(ConfigSourceComparator.java:38)
	at [internal classes]
	at org.eclipse.microprofile.config.ConfigProvider.getConfig(ConfigProvider.java:105)
	at com.ibm.ws.microprofile.config.cdi.ConfigCDIExtension.processConversionType(ConfigCDIExtension.java:153)
	at [internal classes]

[AUDIT   ] CWWKZ0001I: Application io-openliberty-sample-getting-started started in 2.436 seconds.
[AUDIT   ] CWWKF0012I: The server installed the following features: [cdi-2.0, distributedMap-1.0, jaxrs-2.1, jaxrsClient-2.1, jndi-1.0, json-1.0, jsonp-1.1, monitor-1.0, mpConfig-1.4, mpHealth-2.2, mpMetrics-2.3, servlet-4.0, ssl-1.0].
[AUDIT   ] CWWKF0011I: The defaultServer server is ready to run a smarter planet. The defaultServer server started in 8.707 seconds.

```

Could anyone please help me here? Maybe I'm not configuring liberty-maven-plugin properly? What am I missing?

**Comment by mbroz2** [comment]
Apologies for the late response.  The reason you hit the above error is because the sample app expects `/resources/CustomConfigSource.json` to exist at `System.getProperty("user.dir")` (aka, where you ran your java -jar command.

In other words, if you created [/resources/CustomConfigSource.json](https://github.com/OpenLiberty/sample-getting-started/blob/main/resources/CustomConfigSource.json) at the directory where you executed your `java -jar` command, I'd expect the issue to be resolved.

**Comment by rohanKanojia** [comment]
Thanks for your reply!
